systemProp.file.encoding=UTF-8
org.gradle.jvmargs=-Xmx3G -Dfile.encoding=GBK
org.gradle.parallel=true
minecraftVersion=26.1.2
minecraftVersionRange=[26.1.2,)
neoforgeVersion=26.1.2.83
neoforgeVersionRange=[26.1.2.83,)
modLoader=kotlinforforge
modLoaderVersionRange=[6.3.0,)
aquacultureVersion=2.9.2
aquacultureVersionRange=[2.9.2,)
kotlinForForgeVersion=6.3.0
kotlinForForgeVersionRange=[6.3.0,)
jeiVersion=29.16.0.47
modId=lavafishing
modName=Lava Fishing
modLicense=AGPLv3
modVersion=1.3.1
modGroupId=club.redux.sunset
modAuthors=Sunset
modCredits=teddyxlandlee, Wei, Karth, Kun, chen114514
modDescription=A mod which allows you to fish in the lava.
