systemProp.file.encoding=UTF-8
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
kotlin.incremental=false
minecraftVersion=1.20.1
minecraftVersionRange=1.20.1
forgeVersion=47.3.7
forgeVersionRange=[47.3.7,)
#modLoader=javafml
modLoader=kotlinforforge
#modLoaderVersionRange=[47,)
modLoaderVersionRange=[4.12,)
minecraftMappingChannel=parchment
#minecraftMappingChannel=official
minecraftMappingVersion=2023.09.03-1.20.1
#minecraftMappingVersion=1.20.1
aquacultureVersion=2.5.7
aquacultureVersionRange=[2.5.7,)
kotlinForForgeVersion=4.12.0
kotlinForForgeVersionRange=[4.12,)
jeiVersion=15.20.0.129
modId=lavafishing
modName=Lava Fishing
modLicense=AGPLv3
modVersion=1.2.0
modGroupId=club.redux.sunset
modAuthors=Sunset
modCredits=teddyxlandlee, Wei, Karth, Kun, chen114514
modDescription=A mod which allows you to fish in the lava.
