systemProp.file.encoding=UTF-8
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
minecraftVersion=1.21.1
minecraftVersionRange=[1.21.1,)
neoforgeVersion=21.1.217
neoforgeVersionRange=[21.1.217,)
modLoader=kotlinforforge
modLoaderVersionRange=[5.10.0,)
minecraftMappingMinecraftVersion=1.21.1
minecraftMappingVersion=2024.11.17
aquacultureArtifactMinecraftVersion=1.21.1
aquacultureVersion=2.7.18
aquacultureVersionRange=[2.7.18,2.8)
kotlinForForgeVersion=5.10.0
kotlinForForgeVersionRange=[5.10.0,)
jeiVersion=19.27.0.340
modId=lavafishing
modName=Lava Fishing
modLicense=AGPLv3
modVersion=1.2.13
modGroupId=club.redux.sunset
modAuthors=Sunset
modCredits=teddyxlandlee, Wei, Karth, Kun, chen114514
modDescription=A mod which allows you to fish in the lava.

