name: snapshot

on:
  push:
    branches:
      - mc*/dev
  pull_request:
    branches:
      - mc*/dev

concurrency:
  group: snapshot
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: adopt
          java-version: 25

      - name: Checkout Code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Cache Gradle Packages
        uses: actions/cache@v6
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          chmod +x ./gradlew
          ./gradlew runData
          ./gradlew build

      - name: Extract Current Minecraft Version
        id: get_version
        run: echo "minecraft_version=$(grep 'minecraftVersion=' gradle.properties | sed 's/minecraftVersion=//g')" >> $GITHUB_OUTPUT

      - name: Generate Changelog
        uses: dsx137/generate-changelog@v1
        id: get_changelog
        with:
          branch: ${{ github.ref_name }}
          include: snapshot

      - name: Update Snapshot Release
        uses: andelf/nightly-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.minecraft_version }}-snapshot
          name: ${{ steps.get_version.outputs.minecraft_version }}-snapshot-$$-${{ github.run_id }}
          prerelease: true
          body: ${{ steps.get_changelog.outputs.changelog }}
          files: ./build/libs/*-all.jar
