name: stable

on:
  push:
    branches:
      - mc*/release
  pull_request:
    branches:
      - mc*/release

concurrency:
  group: stable
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: adopt
          java-version: 25

      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Cache Gradle Packages
        uses: actions/cache@v6
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          chmod +x ./gradlew
          ./gradlew runData
          ./gradlew build

      - name: Extract Version
        id: get_version
        run: |
          echo "version=$(./gradlew properties --console=plain | grep 'version:'  | sed 's/version:\s*//g')" >> $GITHUB_OUTPUT
          echo "minecraft_version=$(grep 'minecraftVersion=' gradle.properties | sed 's/minecraftVersion=//g')" >> $GITHUB_OUTPUT

      - name: Generate Changelog
        uses: dsx137/generate-changelog@v1
        id: get_changelog
        with:
          branch: ${{ github.ref_name }}
          exclude: snapshot

      - name: Create GitHub Release
        uses: andelf/nightly-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          name: ${{ steps.get_version.outputs.version }}
          prerelease: false
          body: ${{ steps.get_changelog.outputs.changelog }}
          files: build/libs/lavafishing-${{ steps.get_version.outputs.version }}-all.jar

      - name: Modrinth Release
        uses: dsx137/modrinth-releaser@v1
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
        with:
          name: ${{ steps.get_version.outputs.version }}
          project_id: puTJzCb0
          loaders: neoforge
          game_versions: ${{ steps.get_version.outputs.minecraft_version }}
          version_number: ${{ steps.get_version.outputs.version }}
          changelog: ${{ steps.get_changelog.outputs.changelog }}
          version_type: release
          files: build/libs/lavafishing-${{ steps.get_version.outputs.version }}-all.jar
          dependencies: Vl1uNAuy:required, ordsPcFz:required

      - name: CurseForge Release
        uses: itsmeow/curseforge-upload@v3
        with:
          game_endpoint: minecraft
          token: ${{ secrets.CURSEFORGE_TOKEN }}
          display_name: ${{ steps.get_version.outputs.version }}
          project_id: 1035887
          game_versions: Minecraft 26.1:26.1.2,NeoForge,Java 25,Client,Server
          changelog: ${{ steps.get_changelog.outputs.changelog }}
          release_type: release
          file_path: build/libs/lavafishing-${{ steps.get_version.outputs.version }}-all.jar
          relations: aquaculture:requiredDependency,kotlin-for-forge:requiredDependency

      - name: Mcmod Release
        uses: dsx137/mcmod-releaser@v1
        env:
          MCMOD_ACCOUNT: ${{secrets.MCMOD_ACCOUNT}}
        with:
          project_id: 7611
          game_version: ${{ steps.get_version.outputs.minecraft_version }}
          file: build/libs/lavafishing-${{ steps.get_version.outputs.version }}-all.jar
          platforms: java
          loaders: neoforge
